[package]
name = "ogl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.36"
glutin-winit = "0.5.0"
# wfobj = { git = "https://github.com/nidirene/wfobj.git" }
wfobj = { git = "https://github.com/nidirene/wfobj.git" }
image = "*"
noise = "*"
rand = "*"
egui = "*"
egui_glium = "*"
gltf = { version = "1.0", feature = "utils"}