[package]
name = "Inertia"
version = "0.2.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.36"
glutin-winit = "0.5.0"
# wfobj = { git = "https://github.com/nidirene/wfobj.git" }
wfobj = { git = "https://github.com/nidirene/wfobj.git" }
image = "*"
noise = "*"
rand = "*"
egui = { version = "0.29", default-features = false, features = [
  "bytemuck",
  "default_fonts"
] }
egui-winit = { version = "0.29", default-features = false }
egui_glium = "0.29.0"
gltf = { version = "1.4.1" }